/**
  ******************************************************************************
  * @file    ai_app.hpp
  * @brief   On-device audio inference using the stedgeai-generated network
  *          (Core/AI/audio_net*, regenerated by pc_side/ml_pipeline).
  *          Input: a 15,600-sample microphone snapshot (975 ms), converted
  *          to the model's 64 x 96 quantized log-mel tensor.
  ******************************************************************************
  */
#ifndef AI_APP_HPP
#define AI_APP_HPP

#include <cstddef>
#include <cstdint>

namespace aiapp
{

constexpr size_t kMaxClasses = 16;

struct Result
{
  uint8_t topClass;
  uint8_t nClasses;
  float scores[kMaxClasses];
  uint32_t preprocessUs;
  uint32_t inferenceUs;
};

/* Initializes the network once (lazily). Returns false if the runtime
 * failed to initialize - errors are printed to the console. */
bool init();

/* Runs one inference over the current microphone buffer. */
bool runOnce(Result &out);

/* Human-readable class name (from the pipeline-generated label table). */
const char *label(uint8_t cls);

} // namespace aiapp

#endif /* AI_APP_HPP */
