"""End-to-end ML -> firmware pipeline for the B-U585I-IOT02A.

One command takes a (re)trained audio model all the way onto the board:

  1. train    : train the audio classifier -> build/model.tflite   (train.py)
  2. generate : stedgeai CLI -> C code (audio_net.c/h + weights)
  3. integrate: copy generated code + labels header into Secure/Core/AI/
  4. build    : STM32CubeIDE headless build -> .elf / .bin
  5. flash    : ST-LINK (CubeProgrammer CLI)          [board required]
     or ota   : send the .bin over UART/TCP staging   [board required]

Usage:
  python pipeline.py                     # all steps, flash via ST-LINK
  python pipeline.py --steps train,generate,integrate,build
  python pipeline.py --steps build,flash
  python pipeline.py --ota COM9          # stage over UART instead of ST-LINK
  python pipeline.py --skip-train        # reuse build/model.tflite

The dataset (optional) lives in dataset/<class>/*.wav - without it a
synthetic 3-class set (silence/tone/noise) keeps the pipeline runnable.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import shutil
import subprocess
import sys
import time

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HERE = pathlib.Path(__file__).parent
BUILD = HERE / "build"
REPO = HERE.parent.parent
FW_AI_DIR = REPO / "Secure" / "Core" / "AI"
ELF = REPO / "Secure" / "Debug" / "B-U585I-IOT02A_Secure.elf"

STEDGEAI = pathlib.Path(
    r"D:/App/x-cube-ai-windows-v10.2.0/stedgeai-windows-10.2.0/Utilities/windows/stedgeai.exe")
CUBE_IDE = pathlib.Path(
    r"D:/App/ST/STM32CubeIDE_2.1.1/STM32CubeIDE/stm32cubeidec.exe")
GCC_BIN = pathlib.Path(
    r"D:/App/ST/STM32CubeIDE_2.1.1/STM32CubeIDE/plugins"
    r"/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.14.3.rel1"
    r".win32_1.0.100.202602081740/tools/bin")
CUBE_PROG = pathlib.Path(
    r"D:/App/ST/STM32CubeIDE_2.1.1/STM32CubeIDE/plugins"
    r"/com.st.stm32cube.ide.mcu.externaltools.cubeprogrammer"
    r".win32_2.2.400.202601091506/tools/bin/STM32_Programmer_CLI.exe")
HEADLESS_WS = pathlib.Path.home() / "AppData/Local/Temp/claude_hws_ml"


def run(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    print(f"$ {' '.join(str(c) for c in cmd)[:160]}")
    return subprocess.run([str(c) for c in cmd], **kw)


def step_train() -> None:
    print("\n=== [1/5] train ===")
    r = run([sys.executable, HERE / "train.py"])
    if r.returncode != 0:
        raise SystemExit("train failed")


def step_generate() -> None:
    print("\n=== [2/5] stedgeai generate (数分かかります) ===")
    out = BUILD / "stm32ai"
    r = run([STEDGEAI, "generate",
             "--model", BUILD / "model.tflite",
             "--target", "stm32u5",
             "--name", "audio_net",
             "--output", out,
             "--allocate-inputs", "--allocate-outputs"],
            input=b"n\n", timeout=1200)
    if r.returncode != 0 or not (out / "audio_net.c").exists():
        raise SystemExit("stedgeai generate failed")
    report = out / "audio_net_generate_report.txt"
    if report.exists():
        for line in report.read_text(encoding="utf-8", errors="ignore").splitlines():
            if "weights (ro)" in line or "activations (rw)" in line or "macc" in line:
                print(" ", line.strip())


def step_integrate() -> None:
    print("\n=== [3/5] integrate into firmware ===")
    src = BUILD / "stm32ai"
    FW_AI_DIR.mkdir(parents=True, exist_ok=True)
    copied = 0
    for f in src.glob("audio_net*"):
        if f.suffix in (".c", ".h"):
            shutil.copy2(f, FW_AI_DIR / f.name)
            copied += 1
    meta = json.loads((BUILD / "model_meta.json").read_text(encoding="utf-8"))
    classes = meta["classes"]
    labels = ["/* Auto-generated by pc_side/ml_pipeline/pipeline.py - do not edit.",
              " * Class labels matching the trained audio_net model. */",
              "#ifndef AI_LABELS_H", "#define AI_LABELS_H", "",
              f"#define AI_LABELS_COUNT {len(classes)}",
              f"static const char *const AI_LABELS[AI_LABELS_COUNT] = {{"]
    labels += [f'    "{c}",' for c in classes]
    labels += ["};", "", "#endif /* AI_LABELS_H */", ""]
    (FW_AI_DIR / "ai_labels.h").write_text("\n".join(labels), encoding="utf-8")
    print(f"  {copied} network files + ai_labels.h -> {FW_AI_DIR}")
    win = meta["window"]
    if win != 2048:
        print(f"  !! model window {win} != firmware buffer 2048 - adjust telemetry")


def step_build() -> None:
    print("\n=== [4/5] firmware build (headless) ===")
    r = run([CUBE_IDE, "--launcher.suppressErrors", "-nosplash",
             "-application", "org.eclipse.cdt.managedbuilder.core.headlessbuild",
             "-data", HEADLESS_WS,
             "-import", str(REPO / "Secure"),
             "-import", str(REPO / "NonSecure"),
             "-build", "B-U585I-IOT02A_Secure/Debug"],
            capture_output=True, text=True, timeout=900)
    tail = (r.stdout or "") + (r.stderr or "")
    ok = "Build Finished. 0 errors" in tail
    for line in tail.splitlines():
        if "error" in line.lower() or "Build Finished" in line:
            print(" ", line.strip()[:200])
    if not ok:
        raise SystemExit("firmware build failed")
    bin_path = BUILD / "firmware.bin"
    run([GCC_BIN / "arm-none-eabi-objcopy.exe", "-O", "binary", ELF, bin_path])
    print(f"  {bin_path} ({bin_path.stat().st_size} bytes)")


def step_flash() -> None:
    print("\n=== [5/5] flash via ST-LINK ===")
    r = run([CUBE_PROG, "-c", "port=SWD", "mode=UR", "-d", ELF, "-v"],
            capture_output=True, text=True, timeout=300)
    out = (r.stdout or "")
    if "verified successfully" not in out:
        print(out[-600:])
        raise SystemExit("flash failed (ボード接続を確認してください)")
    run([CUBE_PROG, "-c", "port=SWD", "mode=HOTPLUG", "-rst"],
        capture_output=True, timeout=60)
    print("  flashed + reset OK。'i' で単発推論、'I' で2秒毎の自動推論")


def step_ota(target: str) -> None:
    print(f"\n=== [5/5] OTA staging via {target} ===")
    tool = REPO / "pc_side" / "status_monitor" / "ota_update.py"
    arg = ["--tcp", target] if ":" in target else ["--port", target]
    r = run([sys.executable, tool, BUILD / "firmware.bin", *arg], timeout=1200)
    if r.returncode != 0:
        raise SystemExit("OTA staging failed")
    print("  注意: 現状はNORステージングまで（適用ブートローダは次フェーズ）")


def main() -> None:
    ap = argparse.ArgumentParser(description="ML -> STM32 firmware pipeline")
    ap.add_argument("--steps", default="train,generate,integrate,build,flash",
                    help="comma list: train,generate,integrate,build,flash")
    ap.add_argument("--skip-train", action="store_true")
    ap.add_argument("--ota", metavar="COM9|HOST:PORT",
                    help="stage over the OTA link instead of ST-LINK flashing")
    args = ap.parse_args()

    steps = [s.strip() for s in args.steps.split(",") if s.strip()]
    if args.skip_train and "train" in steps:
        steps.remove("train")
    if args.ota and "flash" in steps:
        steps[steps.index("flash")] = "ota"

    t0 = time.time()
    for s in steps:
        if s == "train":
            step_train()
        elif s == "generate":
            step_generate()
        elif s == "integrate":
            step_integrate()
        elif s == "build":
            step_build()
        elif s == "flash":
            step_flash()
        elif s == "ota":
            step_ota(args.ota)
        else:
            raise SystemExit(f"unknown step: {s}")
    print(f"\npipeline done in {time.time() - t0:.0f}s: {' -> '.join(steps)}")


if __name__ == "__main__":
    main()
