/* Auto-generated by pc_side/ml_pipeline/pipeline.py - do not edit.
 * Class labels matching the trained audio_net model. */
#ifndef AI_LABELS_H
#define AI_LABELS_H

#define AI_LABELS_COUNT 3
static const char *const AI_LABELS[AI_LABELS_COUNT] = {
    "silence",
    "tone",
    "noise",
};

#endif /* AI_LABELS_H */
