/* Auto-generated by pc_side/ml_pipeline/pipeline.py - do not edit.
 * Class labels matching the trained audio_net model. */
#ifndef AI_LABELS_H
#define AI_LABELS_H

#define AI_LABELS_COUNT 6
static const char *const AI_LABELS[AI_LABELS_COUNT] = {
    "Crying_and_sobbing",
    "Glass",
    "Gunshot_and_gunfire",
    "Knock",
    "Speech",
    "other",
};

#endif /* AI_LABELS_H */
